# generated by datamodel-codegen:
#   filename:  k8s_swagger.json
#   timestamp: 2022-10-29T09:10:36+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class OperatorVersion(BaseModel):
    __root__: str = Field(
        ...,
        description='OperatorVersion is a wrapper around semver.Version which supports correct marshaling to YAML and JSON.',
    )
